import "server-only";
import Anthropic from "@anthropic-ai/sdk";
import { zodOutputFormat } from "@anthropic-ai/sdk/helpers/zod";
import { CfoReportSchema, type CfoReport } from "./cfo-schema";
import { CFO_SYSTEM_PROMPT, buildCfoUserContent, type CfoPromptInput } from "./cfo-prompt";

const MODEL = "claude-opus-5";
const PROMPT_VERSION = "stage4-v1";

export function isAnthropicConfigured(): boolean {
  return Boolean(process.env.ANTHROPIC_API_KEY);
}

export type CfoGenerationResult = {
  report: CfoReport;
  /** null when no real model call produced this report (not configured, or both attempts failed). */
  model: string | null;
  promptVersion: string;
  rawResponse: unknown;
};

/**
 * A deterministic, non-AI report used when the model is unavailable or
 * fails validation twice. Never fabricates numbers — it only restates the
 * treasury's own already-computed reserve health, and proposes no trades.
 */
function deterministicFallback(input: CfoPromptInput): CfoReport {
  const reserveOk = input.summary ? input.summary.reserve >= input.policy.minimumReserve : true;
  return {
    healthClassification: !input.summary ? "watch" : reserveOk ? "healthy" : "critical",
    summary: input.summary
      ? `Automated fallback report: the Treasury Agent's AI analysis was unavailable. Deterministic reserve check: reserve is ${input.summary.reserve.toFixed(1)}% against a ${input.policy.minimumReserve.toFixed(1)}% minimum.`
      : "Automated fallback report: the Treasury Agent's AI analysis was unavailable and no treasury snapshot has been indexed yet.",
    findings: [],
    warnings: ["This report was generated by a deterministic fallback, not the AI model. No AI-driven trade recommendations were produced."],
    recommendations: [],
  };
}

/**
 * Generates one Treasury Agent report. Never lets the model decide policy
 * compliance — this function only produces a proposed report and
 * recommendations; lib/server/policy/policy-engine.ts independently
 * evaluates every recommendation before it is stored or shown as approvable.
 */
export async function generateCfoReport(input: CfoPromptInput): Promise<CfoGenerationResult> {
  if (!isAnthropicConfigured()) {
    return { report: deterministicFallback(input), model: null, promptVersion: PROMPT_VERSION, rawResponse: null };
  }

  const client = new Anthropic();
  const userContent = buildCfoUserContent(input);

  const attempt = async () => {
    const message = await client.messages.parse({
      model: MODEL,
      max_tokens: 4096,
      thinking: { type: "adaptive" },
      output_config: { format: zodOutputFormat(CfoReportSchema), effort: "high" },
      system: CFO_SYSTEM_PROMPT,
      messages: [{ role: "user", content: userContent }],
    });
    if (message.stop_reason === "refusal") throw new Error("The model declined to generate a report.");
    if (!message.parsed_output) throw new Error("The model did not return a parseable structured report.");
    return message;
  };

  for (let attemptNumber = 1; attemptNumber <= 2; attemptNumber++) {
    try {
      const message = await attempt();
      return { report: message.parsed_output as CfoReport, model: MODEL, promptVersion: PROMPT_VERSION, rawResponse: message };
    } catch (cause) {
      if (attemptNumber === 2) {
        const detail = cause instanceof Error ? cause.message : String(cause);
        const fallback = deterministicFallback(input);
        fallback.warnings.push(`AI generation failed after two attempts: ${detail}`);
        return { report: fallback, model: null, promptVersion: PROMPT_VERSION, rawResponse: null };
      }
    }
  }

  // Unreachable — the loop above always returns on its second iteration.
  return { report: deterministicFallback(input), model: null, promptVersion: PROMPT_VERSION, rawResponse: null };
}
